Notice
fantusya/petly-backend pull request #16
Opened 2023-03-20 13:52 UTC by IvanRoschin

please check my pr

2023-03-20 14:46 UTC, fantusya requested changes

2023-03-20 14:46 UTC, fantusya commented on controllers/notices/getByKeyword.js
> +  const { search: query } = req.params;
`  const { search: query } = req.query;`

2023-03-20 14:46 UTC, fantusya commented on models/pet.js
> +  name: Joi.string().min(2).max(16).pattern(lettersRegexp),
с `required ` это и все поля ниже не работают?

2023-03-20 14:46 UTC, fantusya commented on controllers/notices/addToFavorites.js
> +const addToFavorites = async (req, res) => {
переписать в соответствии с оговорёнными изменениями (по массиву в User)

2023-03-20 14:46 UTC, fantusya commented on controllers/notices/getByCategory.js
> +  const result = await Notice.find({ category }, "-createdAt -updatedAt", {
"-createdAt -updatedAt"
А что это значит? Не в первый раз вижу

2023-03-20 14:46 UTC, fantusya commented on controllers/notices/getFavorite.js
> +const getFavorite = async (req, res) => {
переписать в соответствии с оговорёнными изменениями (по массиву в User)

2023-03-20 14:46 UTC, fantusya commented on controllers/notices/removeFromFavorites.js
> +const removeFromFavorites = async (req, res) => {
переписать в соответствии с оговорёнными изменениями (по массиву в User)

2023-03-20 14:49 UTC, IvanRoschin commented on controllers/notices/getByKeyword.js
> +  const { search: query } = req.params;
ок

2023-03-20 14:50 UTC, IvanRoschin commented on models/pet.js
> +  name: Joi.string().min(2).max(16).pattern(lettersRegexp),
постман почему то не видит поля при required
Предлагаю потестить через фронт

2023-03-20 14:50 UTC, IvanRoschin commented on controllers/notices/addToFavorites.js
> +const addToFavorites = async (req, res) => {
Ок

2023-03-20 14:51 UTC, IvanRoschin commented on controllers/notices/getByCategory.js
> +  const result = await Notice.find({ category }, "-createdAt -updatedAt", {
Это значит что в респонс не будет приходить поля -createdAt -updatedAt

2023-03-20 14:51 UTC, IvanRoschin commented on controllers/notices/getFavorite.js
> +const getFavorite = async (req, res) => {
ок

2023-03-20 14:51 UTC, IvanRoschin commented on controllers/notices/removeFromFavorites.js
> +const removeFromFavorites = async (req, res) => {
ок

2023-03-21 09:12 UTC, fantusya approved these changes

2023-03-21 09:12 UTC, merged