Adds friends model and router
fantusya/petly-backend pull request #8
Opened 2023-03-18 21:28 UTC by AlexRudnyk

Adds friends model and router

2023-03-18 22:48 UTC, fantusya requested changes

2023-03-18 22:48 UTC, fantusya commented on routes/api/friends.js
> +const { friends: ctrl } = require("../../controllers");
Был конфликт между нами, всё пофиксила, только теперь измени здесь `{ friends: ctrl }` на `{ friendsCtrls: ctrl }`

2023-03-18 22:48 UTC, fantusya commented on models/friend.js
> +      type: Array,
Здесь можно не просто `type: Array` указать, а указать в типе схему. Смотри, что на документации предлагают:
![Screenshot_3](https://user-images.githubusercontent.com/100998437/226143957-418b1abd-e6c9-49d4-a3e0-b2e413205165.jpg)
То есть можно прописать мини-подсхему для поля `workDays`. А поля в этой подсхеме такие:
![Screenshot_4](https://user-images.githubusercontent.com/100998437/226144019-f09b7c6e-5f10-4473-a83a-284752260483.jpg)

2023-03-19 12:11 UTC, AlexRudnyk commented on routes/api/friends.js
> +const { friends: ctrl } = require("../../controllers");
поменял

2023-03-19 12:16 UTC, AlexRudnyk commented on models/friend.js
> +      type: Array,
Дописал подсхему и вставил ее, как массив в тип для workDays

2023-03-19 12:48 UTC, fantusya approved these changes

2023-03-19 12:48 UTC, merged